### ISSUE TITLE
更换路径后启动失败

### ISSUE THREAD

**Issue by phields** [wh201906/Proxmark3GUI#15]
---------------------------
proxmark3
---------------------------
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

---------------------------
OK
---------------------------

疑似环境变量遗失

**Comment by wh201906** [comment]
是启动脚本还是客户端路径里面不能包含中文/空格呢？我可以试着在下个版本修复一下

**Comment by phields** [comment]
应该是启动脚本不能包含中文路径，proxmark3.exe会报错Qt组件丢失

**Comment by wh201906** [comment]
Windows对非ASCII字符的支持似乎不是很好，我在启动脚本之前用chcp改代码页也没用
但现在路径中可以包含中文了

It's hard to add non-ASCII support for the path. (or I cann't find a proper way to handle it)
But the app support path with spaces now.
