### ISSUE TITLE
预加载脚本的绝对路径不能包含中文，否则无法执行

### ISSUE THREAD

**Issue by nov12** [wh201906/Proxmark3GUI#17]
系统环境：Win10
软件版本：V0.2.1-win-Officialclient

预加载脚本的绝对路径不能包含中文。
貌似是类似的问题：#15 
比如将包含client的程序解压为至“D:\V0.2.1-win-Officialclient中文”亦或“D:\中文\V0.2.1-win-Officialclient”，预加载脚本则无法执行。

良心软件👍~~

**Comment by wh201906** [comment]
是的，因为程序涉及到调用命令提示符，然后命令提示符似乎不能用QProcess改代码页，所以无法解决。目前我也没有找到有效的解决方案，只能在解压的时候尽量避免含有中文的路径。
