### ISSUE TITLE
Support v4.13441?

### ISSUE THREAD

**Issue by iceman1001** [wh201906/Proxmark3GUI#19]
Latest RRG/Iceman release is v4.13441 
https://github.com/RfidResearchGroup/proxmark3/releases/tag/v4.13441

**Comment by wh201906** [comment]
I‘ll test all features a little bit later.
Kinda busy these days.

**Comment by wh201906** [comment]
The V0.2.2 GUI supports RRG v4.13441.
Theoretically, it can support any new clients by changing the config file, which contains the command format.

**Comment by iceman1001** [comment]
latest release is  v4.14434  ...

**Comment by wh201906** [comment]
Yeah, the developing speed of RRG repo is so fast.
I think the V0.2.2 GUI is compatible with v4.14434 client. I haven't test it yet.

**Comment by wh201906** [comment]
The command format is loaded from config.json now, so the user can try to change this config file if the command format changes.
