### ISSUE TITLE
保存的时候无法保存为dump文件

### ISSUE THREAD

**Issue by lionzhou1981** [wh201906/Proxmark3GUI#21]
当前版本保存的时候只能保存为 txt 文件，无法选择保存为dump文件.

**Comment by wh201906** [comment]
中文翻译文件有问题
你可以在这个[提交记录](https://github.com/wh201906/Proxmark3GUI/tree/02a8fe03e3f08dcea93c9974159425d636dd109a)里面下载lang文件夹里面的zh_CN.ts和zh_CN.qm两个文件，替换掉原来的翻译文件就可以了
