### ISSUE TITLE
Raspberry Pi linux Debian 连接不上pm3

### ISSUE THREAD

**Issue by lkjopp** [wh201906/Proxmark3GUI#22]
rrg/iceman 4.13441 点击连接10次，命令中会显示1次版本hw version，GUI界面一直显示未连接，无反应，按钮灰色

Pm3 log 显示 STDIN unexpected end, exit....

换成老版本rrg/iceman 4.9237，点击连接2次，命令中会显示hw version一次， GUI界面一直未连接，按钮一直灰色，无反应，问题依然存在

Pm3 log 显示 STDIN unexpected end, exit....

**Comment by wh201906** [comment]
手上暂时没有PM3硬件，没办法测试
你可以尝试勾选“设置”面板中的“保持所有按钮可点击”（Settings->Keep buttons enabled），然后试一下能否继续使用
或者使用[该版本](https://github.com/RfidResearchGroup/proxmark3/tree/bb0577f97882c6ea7e41d872643626386f173ced)的RRG固件

**Comment by lkjopp** [comment]
已测试，在“设置”面板中勾选保持所有按钮可点击，依然无效，点击读卡会跳转原始命令，其他按钮没有反应。

您建议的版本是4.13441，是我第一次使用的版本，这两个版本命令行都可以正常使用。

![IMG_20210813_152951.jpg](https://user-images.githubusercontent.com/23353901/129320889-b5c6ebe7-dbe6-4b12-8fa9-1589f58eff4d.jpg)![IMG_20210813_152937.jpg](https://user-images.githubusercontent.com/23353901/129320911-f5dafc0c-56d7-4ac5-b31b-2999d09b12ed.jpg)

**Comment by wh201906** [comment]
可以把pm3的log文件也发上来吗？

**Comment by lkjopp** [comment]
按照你的版本去下载，编译了，刷了pm3，还是不行，GUI连接不上.

**Comment by lkjopp** [comment]
pm3的log放在这儿了

https://github.com/lkjopp/log

**Comment by wh201906** [comment]
收到，到时候调一下

**Comment by wh201906** [comment]
我发现raspbian默认不带qt的开发包，你在编译GUI的时候用的是哪一版Qt？
如果没有用Qt5或者不确定的话可以试下README.md当中的编译命令，我刚才更新过

**Comment by lkjopp** [comment]
我安装了qt5，raspberry pi 可以安装的，虽然有些麻烦。

**Comment by wh201906** [comment]
颜色应该不影响的，我等手上有PM3硬件之后再试试吧

**Comment by wh201906** [comment]
是等待时间和换行符的问题
你可以试一下[这个提交](https://github.com/wh201906/Proxmark3GUI/tree/12a0837c503e3941641640a8ad550811be6f5a82)，我在自己的树莓派上试了下，能用

**Comment by lkjopp** [comment]
多谢，晚上回去试完汇报

**Comment by wh201906** [comment]
后期会跟进的
感谢反馈

**Comment by wh201906** [comment]
我忘记了，之前我做过这种情况的处理的
在你之前使用的版本当中勾选“Keep the client active”（在PM3断开后保持客户端运行）就可以了
