### ISSUE TITLE
Debian Make error

### ISSUE THREAD

**Issue by lkjopp** [wh201906/Proxmark3GUI#25]
/module/lf.cpp line 87 QT::SkipEmptyParts

Make Error : SkipEmptyParts is not a member of QT

Change to QString::SkipEmptyParts 

Make success

May QT5 not support QT::SkipEmptyParts

**Comment by wh201906** [comment]
[Qt::SkipEmptyParts](https://doc.qt.io/qt-5/qt.html#SplitBehaviorFlags-enum) is introduced in Qt 5.14
Before Qt 5.14, the split() function uses [QString::SkipEmptyParts](https://doc.qt.io/qt-5/qstring-obsolete.html#SplitBehavior-enum), which is a obsolete enumerator now.
