### ISSUE TITLE
请求搞个macOS

### ISSUE THREAD

**Issue by micoewhl** [wh201906/Proxmark3GUI#31]
如果在mac下怎么搞呢

**Comment by wh201906** [comment]
按理说是可以在Mac下编译然后运行的，但是因为我目前没Mac的环境，所以无法测试
你可以暂时参考一下其它Qt开源项目在Mac下的编译步骤，然后自行编译试一下

**Comment by micoewhl** [comment]
我在正在看教程学编程，有兴趣，有设备，有环境。如果你需要的话或者可以的话我可以搭把手，正好学习一下，我微信micoewhl，期待和你的合作。

**Comment by hiifong** [comment]
> 我在正在看教程学编程，有兴趣，有设备，有环境。如果你需要的话或者可以的话我可以搭把手，正好学习一下，我微信micoewhl，期待和你的合作。

Mac下你可以提高brew安装相关依赖，跟ubuntu等Linux发行版差不多的

**Comment by wh201906** [comment]
我近期有点忙，所以暂时不会加新功能或者做其它平台的适配。等后面空了再说吧

**Comment by wh201906** [comment]
> 我在正在看教程学编程，有兴趣，有设备，有环境。如果你需要的话或者可以的话我可以搭把手，正好学习一下，我微信micoewhl，期待和你的合作。

你可以尝试在Mac下装Qt相关的开发环境，然后玩一下。

**Comment by rzhq** [comment]
https://github.com/wh201906/Proxmark3GUI/pull/33 除了settings的路径有一点问题，每次需要手动设置，其他功能都可以正常使用
