### ISSUE TITLE
能否支持最新版rrg客户端v4.15864

### ISSUE THREAD

**Issue by xbebhxx3** [wh201906/Proxmark3GUI#37]
能否支持最新版rrg客户端v4.15864
Can it support the latest version of rrg client v4.15864

**Comment by wh201906** [comment]
最新版本V0.2.6已支持RRG客户端v4.15864
https://github.com/wh201906/Proxmark3GUI/releases/tag/V0.2.6
有bug可在issue或discussions里讨论

**Comment by xbebhxx3** [comment]
但是图形化没有支持一些新命令，比如`auto`、`hf mf autopwn`

**Comment by wh201906** [comment]
`hf mf autopwn`预计最近会加进去。单独的`auto`是什么功能？
