### ISSUE TITLE
LF search uses "u" instead of "-u"

### ISSUE THREAD

**Issue by CortezJEL** [wh201906/Proxmark3GUI#43]
LF search uses "u" instead of "-u"

**Comment by wh201906** [comment]
Hi. Which version of client are you using?

**Comment by wh201906** [comment]
The official client uses "u" and the Iceman/RRG client uses "-u".
If you are using the official client, please select the corresponding config file in the "Settings" panel.
![图片](https://user-images.githubusercontent.com/62299611/226499029-76d018a6-1c51-4f9e-875b-5d29104846c2.png)

**Comment by wh201906** [comment]
@CortezJEL Does your problem resolved?
