### ISSUE TITLE
无法连接到PM3硬件

### ISSUE THREAD

**Issue by i-liberty** [wh201906/Proxmark3GUI#57]
![image](https://github.com/wh201906/Proxmark3GUI/assets/18664862/1586013d-c9b0-40af-a0af-4d7072e2a3e5)

pm3.bat --list
[=] Session log D:\V0.2.8-win64-rrg_other-v4.16717\client\/.proxmark3/logs/log_20240129.txt
[=] Using UART port COM3
unknown command:: 0x61334d50[!!] ERROR: cannot communicate with the Proxmark

**Comment by wh201906** [comment]
应该是固件和客户端不匹配，你需要先刷对应版本的固件

**Comment by i-liberty** [comment]
> 应该是固件和客户端不匹配，你需要先刷对应版本的固件

是的 刷完之后可以了 谢谢
