### ISSUE TITLE
Not sure if this is the correct place..

### ISSUE THREAD

**Issue by ApoIIy0n** [wh201906/Proxmark3GUI#58]
Hi,

I'm trying to write a gen3 card, and specifically blk0 when i do

pm3 --> hf mf gen3blk -d 0465809AEC7181884400C820

the result i'm getting is
[+] Current block... 0465809AEC7181084400C82000000000

tried this with multiple fobs, keep getting the same result. so the 8 becomes a 0 after C7181 anyone know why or how this is possible... is it due to a bug or?

**Comment by wh201906** [comment]
You can join the Proxmark3 community and ask your question there.  
https://github.com/RfidResearchGroup/proxmark3?tab=readme-ov-file#official-channels
