### ISSUE TITLE
大神你好 什么时候支持cuid卡 ufuid卡的读写呢

### ISSUE THREAD

**Issue by everone11** [wh201906/Proxmark3GUI#6]
最近发现你用C++写的这个pm3gui 需要刷入冰人的固件才能使用吗

**Comment by wh201906** [comment]
这个GUI和官方固件的兼容性最好，CUID卡和UFUID卡都支持的。CUID卡用正常的读写指令即可操作(包括block0)，UFUID卡在锁卡前可用正常读写指令或者后门指令读写所有块，锁卡后可用正常指令读写除block0以外的所有块

**Comment by everone11** [comment]
哦哦 谢谢大神  那种ultralight卡 也能读取到吗

**Comment by wh201906** [comment]
mifare ultralight的内部格式和普通mifare卡不太一样，建议使用命令行手动读取

**Comment by everone11** [comment]
好的 谢谢
