### ISSUE TITLE
 unable to connect

### ISSUE THREAD

**Issue by ruling** [wh201906/Proxmark3GUI#7]
fixed connect question

**Comment by wh201906** [comment]
Could you please describe how this issue happens?

**Comment by wh201906** [comment]
Seems like the client is not complete.
You can copy the libstdc++-6.dll into the folder where the proxmark3.exe is, then try to use the GUI again.
似乎是你的PM3客户端差一个动态链接库
你可以把libstdc++-6.dll拷贝到proxmark3.exe的所在目录，然后再启动GUI
