### ISSUE TITLE
no member named 'textChanged' in 'QSpinBox'

### ISSUE THREAD

**Issue by jsxyhyj** [wh201906/Proxmark3GUI#9]
win   qt5.12.8  
Proxmark3GUI-master\ui\mf_trailerdecoderdialog.cpp:18: error: no member named 'textChanged' in 'QSpinBox'

Proxmark3GUI-master\ui\mf_trailerdecoderdialog.cpp:18: error: 'textChanged' is not a member of 'QSpinBox'
     connect(ui->C0Box, &QSpinBox::textChanged, this, &MF_trailerDecoderDialog::on_boxChanged);
                                   ^~~~~~~~~~~

**Comment by wh201906** [comment]
Which version are you using? Is it under master branch or dev branch?

**Comment by wh201906** [comment]
I know what the problem is. The signal textChanged() is intruduced in Qt 5.14, which will pass the text with prefix and suffix.
I didn't realize the compatibility there. And I will replace it with valueChanged() because I don't need the prefix and suffix.
Thanks for your issue.
